In [2]:
import cv2

In [3]:
photo = cv2.imread('award.jpg')

In [9]:
cv2.imshow('vimal award'  , photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
photo.shape

(1365, 2048, 3)

In [6]:
photo

array([[[19, 12,  9],
        [19, 12,  9],
        [19, 12,  9],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       [[19, 12,  9],
        [19, 12,  9],
        [19, 12,  9],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       [[19, 12,  9],
        [19, 12,  9],
        [19, 12,  9],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       ...,

       [[ 9,  7,  6],
        [ 9,  7,  6],
        [10,  8,  7],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       [[ 9,  7,  6],
        [ 9,  7,  6],
        [10,  8,  7],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]],

       [[ 9,  7,  6],
        [ 9,  7,  6],
        [10,  8,  7],
        ...,
        [ 9,  7,  6],
        [ 9,  7,  6],
        [ 9,  7,  6]]], dtype=uint8)

In [12]:
newphoto = cv2.cvtColor( photo ,  cv2.COLOR_BGR2GRAY )

In [22]:
cv2.imshow('hi' , newphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
newphoto.shape

(1365, 2048)

In [15]:
newphoto

array([[12, 12, 12, ...,  7,  7,  7],
       [12, 12, 12, ...,  7,  7,  7],
       [12, 12, 12, ...,  7,  7,  7],
       ...,
       [ 7,  7,  8, ...,  7,  7,  7],
       [ 7,  7,  8, ...,  7,  7,  7],
       [ 7,  7,  8, ...,  7,  7,  7]], dtype=uint8)

In [17]:
import numpy as np

In [28]:
c = np.zeros( (200,200)) + 0

In [29]:
cv2.imshow('ji', c)
cv2.waitKey()
cv2.destroyAllWindows()

In [30]:
c

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])